### PR TITLE
Removing duplicate liquibase file

### PR DESCRIPTION
**Pull request by HerbertYiga**
Removing duplicate liquibase file

### CODE REVIEW

**Comment by HerbertYiga** [comment]
investigating why we have duplicate liquibase files on this pr cc @pmanko  @mozzy11

**Comment by mozzy11** [comment]
Thanks @Herbert Yiga for that pr. 
Can you ensure all the changesets in that external liqibase file exist in the liquibase file under the resources??

**Comment by HerbertYiga** [comment]
> Can you ensure all the changesets in that external liqibase file exist in the liquibase file under the resources??

ohh yes!

**Comment by HerbertYiga** [comment]
moving things here https://github.com/IsantePlus/openmrs-module-isanteplus/pull/107 as requested by @pmanko

**Pull request closed without merging**
